### ISSUE TITLE
Mobile App- Master Issue

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#53]
## Background

Currently, the AudioLux device is controlled from a web app that is served to the connecting device when it needs to be used. This implementation has a few issues:

- Any device can receive the web app and have full control just by connecting to the device
- A web browser must be used to control the device, making it less accessible to mobile devices

Therefore, the AudioLux team has determined that a mobile app is the best way to enable control from a mobile device, which is far more accessible to most than a desktop or laptop. As the code for the web app is programmed in Preact, porting to mobile using another flavor of React should be reasonably achievable.

### Functional

- The mobile app must contain the same features as the web app.
- The UI must be optimized for mobile devices.
- The web app must remain functional and updated alongside the mobile app.

### Nonfunctional

- The mobile app must be easy to update with new features.
- The mobile app must be written in React Native.
- The mobile app back end should use a similar codebase to the web app back end.

## Dependencies

- This story is not blocked by or blocking other user stories.

## Subtasks

- [ ] #54
- [ ] #55
- [ ] #56

## Estimate

The Figma design should be complete no later than the end of Fall term, including presentations to the Project Partner.
The mobile app UI should be implemented no later than Week 5 Winter Term.
The mobile app should be fully functional, including new features added to the web app over the year, by the end of Capstone.

## Acceptance Criteria

- [ ] The mobile app can configure the network settings of the device, including AudioLux password and target network.
- [ ] The mobile app can select patterns and configure settings associated with the pattern.
- [ ] The mobile app has feature parity with the web app.

## Definition of Done

- [ ] The feature has well-written inline documentation.
- [ ] The feature has well-written wiki documentation.
- [ ] The pattern has been tested to work with microphone input.
- [ ] The pattern has been tested to work with PC audio input.
- [ ] The feature meets all acceptance criteria.
- [ ] The feature has been demoed to the project partner and, ideally, other stakeholders.
- [ ] The feature has been merged with release code.
- [ ] The feature is included in a minor or major release.
