### ISSUE TITLE
Mobile App- UI Implementation

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#55]
## Background

The AudioLux mobile app will be implemented using React Native. 

### Functional

- The mobile app must contain the same features as the web app.
- The UI must be optimized for mobile devices.
- The mobile app UI must have feature parity with the web app UI.

### Nonfunctional

- The mobile app UI should be designed in Figma.
- The mobile app UI must be accessible to both non-technical users and the hard of hearing.
- The mobile app UI should have the same screen contents as the web app.

## Subtasks

- [ ] Design the paths for configuring the network
- [ ] Design the paths for selecting and configuring LED strip patterns
- [ ] Demo to project partner for final approval.

## Dependencies

- This story is blocked by the following user story: #54 
- This story is blocking the following user story: #56 

## Estimate

The UI should be functional at the latest Week 5 of winter term.

## Acceptance Criteria

- [ ] The mobile app UI has screens and paths that can correspond to setting the network settings of the device, including AudioLux password and target network.
- [ ] The mobile app can screens that can select patterns and configure settings associated with the pattern when later attached to the back end.
- [ ] The mobile app has feature parity with the web app.
- [ ] The UI demo is approved by the project partner.
