### ISSUE TITLE
Z-Layering

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#57]
## Background

CymaSpace stakeholders have requested the ability to run two patterns on top of each other, with the "top" pattern being given some layer of opacity.

### Functional

- The web app must be able to select an additional pattern to run.
- The web app must have the ability to turn Z-Layering on and off.
- The web app must have a slider to change the opacity of the top layer.
- 
### Nonfunctional

- The process for layering two patterns must be computationally simple enough to not slow down audio analysis.

## Subtasks

- [ ] Identify needed code changes to support Z-Layering and present those changes to either the project partner or to the group as a whole.
- [ ] Implement the back end code to support Z-Layering.
- [ ] Make API and web app changes to support Z-Layering.

## Dependencies

- This story is not blocked by or blocking other user stories.

## Estimate

This issue should be complete before the end of fall term, and no later than the start of winter term.

## Acceptance Criteria

- [ ] The web app can assign a pattern to run on top of another.
- [ ] The web app can adjust opacity of the top layer.

**Comment by shillinc-osu** [comment]
Closing this issue as it is complete minus a few bugfixes.
