### ISSUE TITLE
Networking- Cannot connect to AudioLux after inputting incorrect password

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#58]
## Subtasks
- [ ] Identify the cause of the bug.
- [ ] Patch the bug
- [ ] Perform testing to ensure issue is resolved.
