### ISSUE TITLE
LED Strip Simulator V2

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#59]
## Background
The current LED strip simulator is difficult to use and not resistant to disconnects. For example:

- The app crashes when a device is not connected on launch.
- The app crashes when a device is disconnected during operation.
- The simulator opens 3 exceptionally-wide OpenCV windows, making moving them difficult.
- The current simulator needs code changes to set the length of the LED strip.

The current code is actually pretty solid, and just needs some exception handling and a good UI to be a good development tool. The communication protocol is also very simple and has a lot of room to send additional data should we want it.

We will continue to develop in Python due to portability and the interest to reuse code whenever possible.

This feature is out-of-scope, so development should not hinder the development of other more essential features.

## Task List

- [x] Add exception handling to prevent crashes on startup and on disconnect. Provide an error report in terminal.
- [x] Design a UI (likely in PySimpleGUI) to simply house the 3 images generated by OpenCV.
- [x] Add a button to reconnect to the AudioLux if connection fails.
- [x] Automatically set virtual LED strip length based of of incoming data.

## Acceptance Criteria

- [x] The app does not crash when an AudioLux is plugged in or disconnected.
- [x] The app can reconnect to the AudioLux in the event of a disconnection.
- [x] The app sets the length of the LED strip when an AudioLux is transmitting data.

**Comment by shillinc-osu** [comment]
Issue completed, looking to merge.
