### ISSUE TITLE
LED Strip Splitting

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#60]
## Background

Our stakeholders have requested the ability to virtually split an LED strip and run different patterns on each part. This feature will be mutually exclusive with the Z-layering feature.

## Requirements

- The user must be able to press a button on the web app to enable/disable strip splitting.
- The user must be able to select a second pattern on the web app.
- When the button is set to "true" the LED strip will display the first pattern on the first floor(n/2) pixels and the second pattern on the second floor(n/2) pixels.

## Subtasks

- [x] #61
- [x] #62
- [x] #63

## Acceptance Criteria

- [x] The status of the button is set to the ESP32's internal strip splitting boolean value upon first connection.
- [x] When the button is pressed, the button's shown value changes and the Arduino starts strip splitting mode.
- [x] The first pattern is displayed on the first half.
- [x] The second pattern is displayed on the second half.
- [x] When strip splitting is enabled, Z-layering is automatically disabled, and vice versa.

**Comment by shillinc-osu** [comment]
Closing this issue, done aside from minor bugfixes.
