### ISSUE TITLE
Strip Splitting- API code changes

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#62]
## Requirements

- The user must be able to press a button on the web app to enable/disable strip splitting.
- The user must be able to select a second pattern on the web app.

## Subtasks

- [x] Add a second drop down to select patterns and set it to get/put on a different URL.
- [x] Add a button to enable/disable strip splitting

## Acceptance Criteria

- [x] The second pattern selector drop down properly gets the list of all patterns.
- [x] When a pattern is selected, it send the value to the ESP32. The GET request should be successful.
- [x] When the button is pressed, it's value changes and the new value is sent to the ESP32. The GET request should be successful.
