### ISSUE TITLE
Pattern Refactor (master issue)

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#68]
## Background

Right now, the AudioLux has many, many patterns preprogrammed into the device. Our stakeholders request that we not only reduce the number of pre-programmed patterns, but replace their functionality by adding more methods of adjustment to other patterns.

## Subtasks

- [ ] Identify which patterns to remove. The final pattern count should be about 10-15.
- [ ] Determine additional methods of adjustment for the remaining patterns.
- [ ] Pattern Refactor- Additional web app UI elements
- [ ] Pattern Refactor- API additions
- [ ] Pattern Refactor- ESP32 code changes
