### ISSUE TITLE
Pattern Favoriting

### ISSUE THREAD

**Issue by shillinc-osu** [OPEnSLab-OSU/Nanolux#76]
## Background

The ECE capstone team, at some point this year, will be adding an additional dial to load “favorited” patterns. While this feature hasn’t been fully fleshed out yet, we can add pattern favoriting and loading to our internal web app.

## Tasks

- [x]  Create functions to save/load patterns from a JSON file
- [x]  Add web app buttons to select one of 5 saved patterns, and to either load or save that file
- [x]  Add handlers to tell the ESP32 to load a pattern or overwrite an existing pattern

**Comment by shillinc-osu** [comment]
Closing this issue as it is technically complete, but looking to do a revision of networking code to improve usability.
